// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNEwq2vxZG4tL_htjR6lF29SLrXsOmgM',
    appId: '1:671400345944:web:5092053a1fcac5c506a52d',
    messagingSenderId: '671400345944',
    projectId: 'eventspot-3f448',
    authDomain: 'eventspot-3f448.firebaseapp.com',
    storageBucket: 'eventspot-3f448.appspot.com',
    measurementId: 'G-9H2VGC0482',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQfnF0pj7aYdlOUWF4nkhX8PM6p0amNY',
    appId: '1:671400345944:android:b105243f0ba0bca506a52d',
    messagingSenderId: '671400345944',
    projectId: 'eventspot-3f448',
    storageBucket: 'eventspot-3f448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyzPHShhRCJ2bN_naNgyOFUmAsGP9OI_s',
    appId: '1:671400345944:ios:1f0ad42ac47aaadc06a52d',
    messagingSenderId: '671400345944',
    projectId: 'eventspot-3f448',
    storageBucket: 'eventspot-3f448.appspot.com',
    iosBundleId: 'com.example.ems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyzPHShhRCJ2bN_naNgyOFUmAsGP9OI_s',
    appId: '1:671400345944:ios:c893b4507c3ae53906a52d',
    messagingSenderId: '671400345944',
    projectId: 'eventspot-3f448',
    storageBucket: 'eventspot-3f448.appspot.com',
    iosBundleId: 'com.example.ems.RunnerTests',
  );
}
